[project]
name = "radiocal"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "flask>=3.1.1",
    "icalendar>=6.3.1",
    "lxml>=6.0.0",
    "pandas>=2.3.1",
    "requests>=2.32.5",
]
